# Generated by Django 5.1.6 on 2025-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_workoutlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutperformance',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
